package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1



/**
 * Chinhanh generated by hbm2java
 */
public class Chinhanh  implements java.io.Serializable {


     private Integer maCn;
     private String tenChiNhanh;
     private String diaChi;
     private String quan;
     private String thanhPho;
     private String khuVuc;
     private String soDienThoai;
     private String soFax;

    public Chinhanh() {
        this.maCn = 1;
        this.tenChiNhanh = "test2";
        this.diaChi = "test2";
        this.quan = "test2";
        this.thanhPho = "test2";
        this.khuVuc = "test2";
        this.soDienThoai = "test2";
        this.soFax = "test2";
    }

	
    public Chinhanh(String tenChiNhanh, String diaChi, String quan, String thanhPho, String khuVuc) {
        this.tenChiNhanh = tenChiNhanh;
        this.diaChi = diaChi;
        this.quan = quan;
        this.thanhPho = thanhPho;
        this.khuVuc = khuVuc;
    }
    public Chinhanh(String tenChiNhanh, String diaChi, String quan, String thanhPho, String khuVuc, String soDienThoai, String soFax) {
       this.tenChiNhanh = tenChiNhanh;
       this.diaChi = diaChi;
       this.quan = quan;
       this.thanhPho = thanhPho;
       this.khuVuc = khuVuc;
       this.soDienThoai = soDienThoai;
       this.soFax = soFax;
    }
   
    public Integer getMaCn() {
        return this.maCn;
    }
    
    public void setMaCn(Integer maCn) {
        this.maCn = maCn;
    }
    public String getTenChiNhanh() {
        return this.tenChiNhanh;
    }
    
    public void setTenChiNhanh(String tenChiNhanh) {
        this.tenChiNhanh = tenChiNhanh;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getQuan() {
        return this.quan;
    }
    
    public void setQuan(String quan) {
        this.quan = quan;
    }
    public String getThanhPho() {
        return this.thanhPho;
    }
    
    public void setThanhPho(String thanhPho) {
        this.thanhPho = thanhPho;
    }
    public String getKhuVuc() {
        return this.khuVuc;
    }
    
    public void setKhuVuc(String khuVuc) {
        this.khuVuc = khuVuc;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getSoFax() {
        return this.soFax;
    }
    
    public void setSoFax(String soFax) {
        this.soFax = soFax;
    }




}


