package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1



/**
 * Chunha generated by hbm2java
 */
public class Chunha  implements java.io.Serializable {


     private Integer maChuNha;
     private String hoTen;
     private String diaChi;
     private String soDienThoai;

    public Chunha() {
    }

	
    public Chunha(String hoTen, String diaChi) {
        this.hoTen = hoTen;
        this.diaChi = diaChi;
    }
    public Chunha(String hoTen, String diaChi, String soDienThoai) {
       this.hoTen = hoTen;
       this.diaChi = diaChi;
       this.soDienThoai = soDienThoai;
    }
   
    public Integer getMaChuNha() {
        return this.maChuNha;
    }
    
    public void setMaChuNha(Integer maChuNha) {
        this.maChuNha = maChuNha;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }




}


