package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hopdong generated by hbm2java
 */
public class Hopdong  implements java.io.Serializable {


     private Integer maHd;
     private Integer maNha;
     private Integer maChuNha;
     private Integer maNt; // ma nguoi thue
     private Date ngayKyHd;
     private Date ngayBatDauHd;
     private Date ngayKetThucHd;
     private Float tienThue1thang;
     private float tienCoc;
     private Integer maNv;

    public Hopdong() {
    }

	
    public Hopdong(Date ngayKyHd, Date ngayBatDauHd, Date ngayKetThucHd, float tienCoc) {
        this.ngayKyHd = ngayKyHd;
        this.ngayBatDauHd = ngayBatDauHd;
        this.ngayKetThucHd = ngayKetThucHd;
        this.tienCoc = tienCoc;
    }
    public Hopdong(Integer maNha, Integer maChuNha, Integer maNt, Date ngayKyHd, Date ngayBatDauHd, Date ngayKetThucHd, Float tienThue1thang, float tienCoc, Integer maNv) {
       this.maNha = maNha;
       this.maChuNha = maChuNha;
       this.maNt = maNt;
       this.ngayKyHd = ngayKyHd;
       this.ngayBatDauHd = ngayBatDauHd;
       this.ngayKetThucHd = ngayKetThucHd;
       this.tienThue1thang = tienThue1thang;
       this.tienCoc = tienCoc;
       this.maNv = maNv;
    }
   
    public Integer getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(Integer maHd) {
        this.maHd = maHd;
    }
    public Integer getMaNha() {
        return this.maNha;
    }
    
    public void setMaNha(Integer maNha) {
        this.maNha = maNha;
    }
    public Integer getMaChuNha() {
        return this.maChuNha;
    }
    
    public void setMaChuNha(Integer maChuNha) {
        this.maChuNha = maChuNha;
    }
    public Integer getMaNt() {
        return this.maNt;
    }
    
    public void setMaNt(Integer maNt) {
        this.maNt = maNt;
    }
    public Date getNgayKyHd() {
        return this.ngayKyHd;
    }
    
    public void setNgayKyHd(Date ngayKyHd) {
        this.ngayKyHd = ngayKyHd;
    }
    public Date getNgayBatDauHd() {
        return this.ngayBatDauHd;
    }
    
    public void setNgayBatDauHd(Date ngayBatDauHd) {
        this.ngayBatDauHd = ngayBatDauHd;
    }
    public Date getNgayKetThucHd() {
        return this.ngayKetThucHd;
    }
    
    public void setNgayKetThucHd(Date ngayKetThucHd) {
        this.ngayKetThucHd = ngayKetThucHd;
    }
    public Float getTienThue1thang() {
        return this.tienThue1thang;
    }
    
    public void setTienThue1thang(Float tienThue1thang) {
        this.tienThue1thang = tienThue1thang;
    }
    public float getTienCoc() {
        return this.tienCoc;
    }
    
    public void setTienCoc(float tienCoc) {
        this.tienCoc = tienCoc;
    }
    public Integer getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(Integer maNv) {
        this.maNv = maNv;
    }




}


