package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1



/**
 * Loainha generated by hbm2java
 */
public class Loainha  implements java.io.Serializable {


     private Integer maLoai;
     private String tenLoai;

    public Loainha() {
    }

    public Loainha(String tenLoai) {
       this.tenLoai = tenLoai;
    }
   
    public Integer getMaLoai() {
        return this.maLoai;
    }
    
    public void setMaLoai(Integer maLoai) {
        this.maLoai = maLoai;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }




}


