package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1



/**
 * Nguoithue generated by hbm2java
 */
public class Nguoithue  implements java.io.Serializable {


     private Integer maNt;
     private String hoTen;
     private String diaChi;
     private String dienThoai;
     private Integer chiNhanhQuanLy;

    public Nguoithue() {
    }

	
    public Nguoithue(String hoTen, String diaChi) {
        this.hoTen = hoTen;
        this.diaChi = diaChi;
    }
    public Nguoithue(String hoTen, String diaChi, String dienThoai, Integer chiNhanhQuanLy) {
       this.hoTen = hoTen;
       this.diaChi = diaChi;
       this.dienThoai = dienThoai;
       this.chiNhanhQuanLy = chiNhanhQuanLy;
    }
   
    public Integer getMaNt() {
        return this.maNt;
    }
    
    public void setMaNt(Integer maNt) {
        this.maNt = maNt;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public Integer getChiNhanhQuanLy() {
        return this.chiNhanhQuanLy;
    }
    
    public void setChiNhanhQuanLy(Integer chiNhanhQuanLy) {
        this.chiNhanhQuanLy = chiNhanhQuanLy;
    }




}


