package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien implements java.io.Serializable {

    private Integer maNv;
    private String hoTen;
    private String diaChi;
    private String gioiTinh;
    private Float luong;
    private Integer chiNhanhLamViec;
    private String soDienThoai;

    public Nhanvien() {
    }

    public Nhanvien(String hoTen, String diaChi) {
        this.hoTen = hoTen;
        this.diaChi = diaChi;
    }

    public Nhanvien(String hoTen, String diaChi, String gioiTinh, Float luong, Integer chiNhanhLamViec, String soDienThoai) {
        this.hoTen = hoTen;
        this.diaChi = diaChi;
        this.gioiTinh = gioiTinh;
        this.luong = luong;
        this.chiNhanhLamViec = chiNhanhLamViec;
        this.soDienThoai = soDienThoai;
    }

    public Integer getMaNv() {
        return this.maNv;
    }

    public void setMaNv(Integer maNv) {
        this.maNv = maNv;
    }

    public String getHoTen() {
        return this.hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    public String getDiaChi() {
        return this.diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getGioiTinh() {
        return this.gioiTinh;
    }

    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    public Float getLuong() {
        return this.luong;
    }

    public void setLuong(Float luong) {
        this.luong = luong;
    }

    public Integer getChiNhanhLamViec() {
        return this.chiNhanhLamViec;
    }

    public void setChiNhanhLamViec(Integer chiNhanhLamViec) {
        this.chiNhanhLamViec = chiNhanhLamViec;
    }

    public String getSoDienThoai() {
        return soDienThoai;
    }

    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    
}
