package pojos;
// Generated Sep 27, 2019 9:45:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NhaNvphutrach generated by hbm2java
 */
public class NhaNvphutrach  implements java.io.Serializable {


     private int maNha;
     private int maNv;
     private Date ngayBatDau;
     private Date ngayKetThuc;

    public NhaNvphutrach() {
    }

    public NhaNvphutrach(int maNha, int maNv, Date ngayBatDau, Date ngayKetThuc) {
       this.maNha = maNha;
       this.maNv = maNv;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
    }

    public int getMaNha() {
        return maNha;
    }

    public void setMaNha(int maNha) {
        this.maNha = maNha;
    }

    public int getMaNv() {
        return maNv;
    }

    public void setMaNv(int maNv) {
        this.maNv = maNv;
    }
   
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }




}


